### ISSUE TITLE
"$ operator is invalid for atomic vectors" error

### ISSUE THREAD

**Issue by jicyang** [Azure/AzureKusto#5]
I think AzureKusto could be a great tool for data scientist using R. But I have trouble to set it up correctly. After I installed AzureKusto library, I run the following code but got an error: 

testpoint<-kusto_database_endpoint(server="https://kusto.xxxx.microsoft.com",database="test")
res2<-run_query(testpoint, "buildsetcalculator | take 20")

The second line throws out an error as follows:
> res2<-run_query(testpoint, "buildsetcalculator | take 20")
Error: $ operator is invalid for atomic vectors

Even if I run an incorrect query as follows, the error is same
res2<-run_query(testpoint, "dfasqrwe")

Unlike the server address used in example, this cluster server address has the name of cluster 'xxxx' behind 'kusto'. It may be the reason. 
 
Thanks for developing AzureKusto!

**Comment by hongooi73** [comment]
Per emails, this is because the internal Aria tool uses its own authentication mechanism
